# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content',
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
